title: Zhang Xu's Homepage
page-top-title: Zhang Xu
top-section-bg-text: Economics
home-subtitle: Zhang XU&ensp;|&ensp;徐张
footer: Updated: Feb 2026&ensp;|&ensp;Forked from <a href="https://github.com/senli1073/academic-homepage-template" target="_blank" rel="noopener noreferrer">senli1073</a>
